---
name: mvn
"on":
  push:
    branches:
      - master
    paths-ignore: ['paper/**', 'sandbox/**']
  pull_request:
    branches:
      - master
    paths-ignore: ['paper/**', 'sandbox/**']
jobs:
  maven-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        java: [11, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Show versions
        run: java -version; mvn -version;
      - name: Build it with Maven
        run: mvn -B clean install -Pqulice
  pdd-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: g4s8/pdd-action@master
